// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações nesse arquivo podem causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>

namespace DesafioFinalCaixaverso.Exceptions;

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

#nullable enable

/// <summary>
///   Uma classe de recurso fortemente tipada, para pesquisar cadeias de caracteres localizadas etc.
/// </summary>
[CompilerGenerated]
[GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "8.0.0.0")]
[SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
public class MensagensDeExcecao
{
    private static ResourceManager? recurso;

    private static CultureInfo? cultura;

    /// <summary>
    ///   Retorna a instância de ResourceManager em cache usada por essa classe.
    /// </summary>
    public static ResourceManager Recurso => recurso ??= new ResourceManager("DesafioFinalCaixaverso.Exceptions.MensagensDeExcecao", typeof(MensagensDeExcecao).Assembly);

    /// <summary>
    ///   Substitui a propriedade CurrentUICulture do thread atual para todas as pesquisas de recursos usando essa classe de recurso fortemente tipada.
    /// </summary>
    public static CultureInfo? Cultura
    {
        get => cultura;
        set => cultura = value;
    }

    public static string CLIENTE_ID_INVALIDO => Recurso.GetString("CLIENTE_ID_INVALIDO", cultura)!;

    public static string CLIENTE_NAO_ENCONTRADO => Recurso.GetString("CLIENTE_NAO_ENCONTRADO", cultura)!;

    public static string CLIENTE_NOME_OBRIGATORIO => Recurso.GetString("CLIENTE_NOME_OBRIGATORIO", cultura)!;

    public static string CLIENTE_EMAIL_OBRIGATORIO => Recurso.GetString("CLIENTE_EMAIL_OBRIGATORIO", cultura)!;

    public static string CLIENTE_EMAIL_INVALIDO => Recurso.GetString("CLIENTE_EMAIL_INVALIDO", cultura)!;

    public static string CLIENTE_SENHA_MINIMA => Recurso.GetString("CLIENTE_SENHA_MINIMA", cultura)!;

    public static string CLIENTE_EMAIL_JA_CADASTRADO => Recurso.GetString("CLIENTE_EMAIL_JA_CADASTRADO", cultura)!;

    public static string TIPO_PRODUTO_OBRIGATORIO => Recurso.GetString("TIPO_PRODUTO_OBRIGATORIO", cultura)!;

    public static string PRAZO_SIMULACAO_INVALIDO => Recurso.GetString("PRAZO_SIMULACAO_INVALIDO", cultura)!;

    public static string VALOR_SIMULACAO_MINIMO => Recurso.GetString("VALOR_SIMULACAO_MINIMO", cultura)!;

    public static string PRODUTO_NAO_ENCONTRADO => Recurso.GetString("PRODUTO_NAO_ENCONTRADO", cultura)!;

    public static string ERRO_DESCONHECIDO => Recurso.GetString("ERRO_DESCONHECIDO", cultura)!;

    public static string QUESTIONARIO_HORIZONTE_INVALIDO => Recurso.GetString("QUESTIONARIO_HORIZONTE_INVALIDO", cultura)!;

    public static string QUESTIONARIO_RENDA_INVALIDA => Recurso.GetString("QUESTIONARIO_RENDA_INVALIDA", cultura)!;

    public static string QUESTIONARIO_PATRIMONIO_INVALIDO => Recurso.GetString("QUESTIONARIO_PATRIMONIO_INVALIDO", cultura)!;

    public static string QUESTIONARIO_TOLERANCIA_INVALIDA => Recurso.GetString("QUESTIONARIO_TOLERANCIA_INVALIDA", cultura)!;

    public static string SEGURANCA_CONFIG_HASH_NAO_INFORMADA => Recurso.GetString("SEGURANCA_CONFIG_HASH_NAO_INFORMADA", cultura)!;

    public static string SEGURANCA_CHAVE_HASH_OBRIGATORIA => Recurso.GetString("SEGURANCA_CHAVE_HASH_OBRIGATORIA", cultura)!;
}
